---
title: "Ec/ACM/CS 112. Problem set 1. Template "
output:
  html_notebook: default
  pdf_document: default
---


# Step 1: Programming stochastic simulations

## 1.A
```{r}
x1 = rnorm(1000, mean = 10, sd = 10)
x2 = rnorm(1000, mean = 10, sd = 10)
mean_x1 = mean(x1)
mean_x2 = mean(x2)
plot(x1, x2, main = "random seed unspecified", xlim=c(-50, 50), 
     ylim=c(-50, 50), pch=16, col=rgb(1, 0, 0, alpha = 0.3))
abline(h = mean_x2, lty=2)
abline(v = mean_x1, lty=2)
text(-35, -5, paste("mean x1 = ", round(mean_x1, 2)))
text(-33, -10, paste("mean x2 = ", round(mean_x2, 2)))
```
## 1.B
```{r}
set.seed(2021)
x1 = rnorm(1000, mean = 10, sd = 10)
set.seed(2021)
x2 = rnorm(1000, mean = 10, sd = 10)
mean_x1 = mean(x1)
mean_x2 = mean(x2)
plot(x1, x2, main = "random seed specified", xlim=c(-50, 50), 
     ylim=c(-50, 50), pch=16, col=rgb(1, 0, 0, alpha = 0.3))
abline(a=0, b=1, lty=2)
text(-35, -5, paste("mean x1 = ", round(mean_x1, 2)))
text(-33, -10, paste("mean x2 = ", round(mean_x2, 2)))


```
# Step 2: Simulating the hot-hand in basketball

## 2.A
```{r}
simulate_player <- function(p_score) {
  return (rbinom(25, 1, p_score))
}

count_sequence <- function(shots) {
  max_streak = 0
  curr_streak = 0
  for (shot in shots) {
    if (shot == 0) {
      max_streak = max(curr_streak, max_streak)
      curr_streak = 0
    }
    else {
      curr_streak = curr_streak + 1
    }
  }
  return (max_streak)
}
```

## 2.B
```{r}
set.seed(2024)
x = c()
for (i in 1:10000) {
  x[i] = count_sequence(simulate_player(0.5))
}
hist(x, col="white", main="Distribution of longest streaks",
     xlab="size of longest streak", ylab="")
abline(v=mean(x), lty=2, col="red", lwd=2)
text(10, 1000, paste("mean = ", round(mean(x), 2)))
text(10, 700, paste("min = ", min(x)))
text(10, 400, paste("max = ", max(x)))

```

## 2.C
```{r}
pHits = seq(from=0.1, to=0.9, by=0.05)
mean_pHit = c()
max_pHit = c()
min_pHit = c()
x = c()
curr_pHit = 1
for (pHit in pHits) {
  for (i in (1:10000)) {
    x[i] = count_sequence(simulate_player(pHit))
  }
  mean_pHit[curr_pHit] = mean(x)
  max_pHit[curr_pHit] = max(x)
  min_pHit[curr_pHit] = min(x)
  curr_pHit = curr_pHit + 1
}
plot(pHits, mean_pHit, col="blue", pch=16, xlim=c(0.0, 1.0), ylim=c(0, 25),
     type="o", xlab="prob score", ylab="streak length")
points(pHits, max_pHit, col="green", type="l", lty=2)
points(pHits, min_pHit, col="red", type="l", lty=2)
legend("topleft", legend=c("mean", "max", "min"), bty='n', col=c("blue", "green", "red"),
       lty=c(1, 2, 2))
```


